/*
	File: fn_itemWeight.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Gets the items weight and returns it.
*/
private["_item"];
_item = [_this,0,"",[""]] call BIS_fnc_param;
if(_item == "") exitWith {};

switch (_item) do
{
    case "bier": {2};
	case "wodka": {2};
	case "wein": {2};
	case "schwarz": {2};
    case "roggen": {3};
	case "hefe": {3};
	case "hopfen": {3};
	case "trauben": {3};
    case "henrap": {3};
	case "roosterrap": {1};
	case "goatrap": {1};
	case "sheeprap": {2};
	case "rabbitrap": {1};
    case "henraw": {2};
	case "roosterraw": {2};
	case "goatraw": {3};
	case "sheepraw": {4};
	case "rabbitraw": {2};
    case "ring": {2};
    case "seide": {2};
    case "kunstoff": {2};
    case "reifenu": {4};
	case "reifenp": {3};
    case "holzu": {6};
	case "holzp": {3};
    case "baumwolleu": {3};
	case "baumwollep": {1};
	case "oilu": {6};
	case "oilp": {4};
	case "silberu": {4};
	case "goldu": {5};
	case "silberp": {2};
	case "goldp": {2};
	case "heroinu": {6};
	case "heroinp": {4};
	case "cannabis": {6};
	case "marijuana": {4};
	case "apple": {1};
	case "water": {1};
	case "rabbit": {1};
	case "salema": {2};
	case "ornate": {2};
	case "mackerel": {4};
	case "tuna": {6};
	case "mullet": {4};
	case "catshark": {6};
	case "turtle": {8};
	case "fishing": {2};
	case "turtlesoup": {2};
	case "donuts": {1};
	case "coffee": {1};
	case "fuelE": {2};
	case "fuelF": {5};
	case "money": {0};
	case "pickaxe": {2};
	case "copperore": {2};
	case "ironore": {2};
	case "copper_r": {1};
	case "iron_r": {2};
	case "sand": {3};
	case "salt": {5};
	case "salt_r": {3};
	case "glass": {1};
	case "diamond": {4};
	case "diamondc": {2};
	case "cocaine": {6};
	case "cocainep": {5};
	case "spikeStrip": {5};
	case "rock": {6};
	case "cement": {5};
	case "goldbar": {10};
	case "wine": {5};
	case "grapes": {3};
	case "methu": {6};
	case "methp": {4};
	case "battery": {1};
	case "blastingcharge": {30};
	case "boltcutter": {10};
	case "defusekit": {1};
	case "painkillers": {5};
	case "morphium": {6};
	case "zipties": {1};
	case "storagesmall": {10};
	case "storagebig": {20};
	case "mauer": {15};
	case "rye": {3};
	case "hops": {3};
	case "yeast": {3};
	case "cornmeal": {2};
	case "mash": {4};
	case "whiskey": {5};
	case "beerp": {4};
	case "moonshine": {5};
	case "bottledwhiskey": {5};
	case "bottledbeer": {5};
	case "bottledshine": {5};
	case "bottles": {1};
	case "puranium": {6};
    case "ipuranium": {3};
    case "uranium1": {2};
    case "uranium2": {1};
    case "uranium3": {4};
    case "uranium4": {4};
    case "uranium": {4};
	case "kidney": {20};
	case "scalpel": {5};
	case "peach": {2};
	default {1};
};
